version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    labels:
      - "github-actions"
      - "dependencies"
    groups:
      github-actions:
        update-types:
          - "major"
          - "minor"
          - "patch"
