version: 2
updates:

  # Check for updates to GitHub Actions every week
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "github-actions"
      - "dependencies"
    groups:
      github-actions:
        update-types:
          - "major"
          - "minor"
          - "patch"

  # Check for updates to gradle dependencies every week
  # Only group non-breaking dependencies to a single pull request
  # Breaking changes via separate pull requests
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "gradle"
      - "dependencies"
    groups:
      non-breaking:
        update-types:
          - "minor"
          - "patch"
